import type { SpatialObject } from "@/lib/spatialTypes";

function vec3(x: number, y: number, z: number) {
  return { x, y, z };
}

export const SOLAR_SYSTEM_OBJECTS: SpatialObject[] = [
  {
    id: "sun",
    kind: "star",
    label: "Sun",
    color: "#f8b400",
    position: vec3(0, 0, 0),
    rotation: vec3(0, 0, 0),
    scale: vec3(1.6, 1.6, 1.6),
    defaultPosition: vec3(0, 0, 0),
    defaultRotation: vec3(0, 0, 0),
    defaultScale: vec3(1.6, 1.6, 1.6),
    hovered: false,
    selected: false,
    grabbed: false,
    physicsEnabled: false,
    radius: 1,
  },
  {
    id: "mercury",
    kind: "planet",
    label: "Mercury",
    color: "#a6a6a6",
    position: vec3(2.2, 0, 0),
    rotation: vec3(0, 0, 0),
    scale: vec3(0.25, 0.25, 0.25),
    defaultPosition: vec3(2.2, 0, 0),
    defaultRotation: vec3(0, 0, 0),
    defaultScale: vec3(0.25, 0.25, 0.25),
    hovered: false,
    selected: false,
    grabbed: false,
    physicsEnabled: false,
    radius: 0.32,
    orbitalRadius: 2.2,
    orbitalSpeed: 1.2,
  },
  {
    id: "venus",
    kind: "planet",
    label: "Venus",
    color: "#d4a373",
    position: vec3(3.2, 0, 0),
    rotation: vec3(0, 0, 0),
    scale: vec3(0.38, 0.38, 0.38),
    defaultPosition: vec3(3.2, 0, 0),
    defaultRotation: vec3(0, 0, 0),
    defaultScale: vec3(0.38, 0.38, 0.38),
    hovered: false,
    selected: false,
    grabbed: false,
    physicsEnabled: false,
    radius: 0.42,
    orbitalRadius: 3.2,
    orbitalSpeed: 0.92,
  },
  {
    id: "earth",
    kind: "planet",
    label: "Earth",
    color: "#4ea8de",
    position: vec3(4.5, 0, 0),
    rotation: vec3(0, 0, 0),
    scale: vec3(0.42, 0.42, 0.42),
    defaultPosition: vec3(4.5, 0, 0),
    defaultRotation: vec3(0, 0, 0),
    defaultScale: vec3(0.42, 0.42, 0.42),
    hovered: false,
    selected: false,
    grabbed: false,
    physicsEnabled: false,
    radius: 0.46,
    orbitalRadius: 4.5,
    orbitalSpeed: 0.8,
  },
  {
    id: "mars",
    kind: "planet",
    label: "Mars",
    color: "#d00000",
    position: vec3(5.9, 0, 0),
    rotation: vec3(0, 0, 0),
    scale: vec3(0.32, 0.32, 0.32),
    defaultPosition: vec3(5.9, 0, 0),
    defaultRotation: vec3(0, 0, 0),
    defaultScale: vec3(0.32, 0.32, 0.32),
    hovered: false,
    selected: false,
    grabbed: false,
    physicsEnabled: false,
    radius: 0.36,
    orbitalRadius: 5.9,
    orbitalSpeed: 0.68,
  },
  {
    id: "jupiter",
    kind: "planet",
    label: "Jupiter",
    color: "#c77d4d",
    position: vec3(8.1, 0, 0),
    rotation: vec3(0, 0, 0),
    scale: vec3(0.92, 0.92, 0.92),
    defaultPosition: vec3(8.1, 0, 0),
    defaultRotation: vec3(0, 0, 0),
    defaultScale: vec3(0.92, 0.92, 0.92),
    hovered: false,
    selected: false,
    grabbed: false,
    physicsEnabled: false,
    radius: 0.88,
    orbitalRadius: 8.1,
    orbitalSpeed: 0.44,
  },
];
